name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - name: Set up MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        update: true
        pacboy: gcc:p cmake:p ninja:p make:p
    - name: Set up vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 53bef8994c541b6561884a8395ea35715ece75db
    - name: Configure
      run: cmake --preset=release-mingw-x86_64
    - name: Build
      run: cmake --build --preset=release-mingw-x86_64
    - uses: actions/upload-artifact@v4
      with:
        name: melonDS-windows-x86_64
        path: .\build\release-mingw-x86_64\melonDS.exe
