name: Windows

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - ci/more-windows-stuff

jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git ppkgconf
        pacboy: >-
          gcc:p cmake:p ninja:p SDL2:p qt5-static:p libarchive:p

    - name: Configure
      run: cmake -B build -DBUILD_STATIC=ON -DCMAKE_PREFIX_PATH=/ucrt64/qtr5-static

    - name: Build
      run: cmake --build .

    - uses: actions/upload-artifact@v1
      with:
        name: melonDS-windows-x86_64
        path: ${{runner.workspace}}\build\melonDS.exe
